name: Replace Pages URL
on: push
jobs:
  replace-url:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3
      
      # Get Pages URL and store in environment
      - name: Get Pages URL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          url=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.html_url')
          echo "PAGES_URL=$url" >> $GITHUB_ENV
      
      # Replace variable in file
      - name: Replace Variable
        run: |
          sed -i "s/__GITHUB_PAGES_URL__/${PAGES_URL}/g" tcr-builders/components/loader.js